# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazyworktree" do
  name "lazyworktree"
  desc "lazyworktree - A TUI tool to manage git worktrees"
  homepage "https://github.com/chmouel/lazyworktree"
  version "1.26.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazyworktree"
  depends_on formula: [
      "git",
      "git-delta",
      "lazygit",
      "less",
      "tmux",
    ]

  on_macos do
    url "https://github.com/chmouel/lazyworktree/releases/download/v#{version}/lazyworktree_Darwin_all.tar.gz"
    sha256 "e401fd8100ee59e6091ca4010f6603b6269d80e1b65dd37a5f2214610b9648a4"
  end

  on_linux do
    on_intel do
      url "https://github.com/chmouel/lazyworktree/releases/download/v#{version}/lazyworktree_Linux_x86_64.tar.gz"
      sha256 "7d2f0ad61128af729dd2c5db8be83fe41a502c51a21440b378822a7fce8c6238"
    end
    on_arm do
      url "https://github.com/chmouel/lazyworktree/releases/download/v#{version}/lazyworktree_Linux_arm64.tar.gz"
      sha256 "8a01b00225ef44fea1875a1af758d9277af9b880761e1de334cd2f92b640d466"
    end
  end

  # No zap stanza required
end
