# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazyworktree" do
  name "lazyworktree"
  desc "lazyworktree - A TUI tool to manage git worktrees"
  homepage "https://github.com/chmouel/lazyworktree"
  version "1.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazyworktree"

  on_macos do
    url "https://github.com/chmouel/lazyworktree/releases/download/v#{version}/lazyworktree_Darwin_all.tar.gz"
    sha256 "d0289fbd243a2efcbff965f32867cb62647e4a0b19e7811920fef57e3c327fd7"
  end

  on_linux do
    on_intel do
      url "https://github.com/chmouel/lazyworktree/releases/download/v#{version}/lazyworktree_Linux_x86_64.tar.gz"
      sha256 "a1a69a230ca1b754b16ae07829fe0bd599da2ea6ec7488b8e200835705e3d586"
    end
    on_arm do
      url "https://github.com/chmouel/lazyworktree/releases/download/v#{version}/lazyworktree_Linux_arm64.tar.gz"
      sha256 "0802185232628c7f41053a77b807d87f8ddaa9ae17de68a0a482728b97e40c21"
    end
  end

  # No zap stanza required
end
