# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazyworktree" do
  name "lazyworktree"
  desc "lazyworktree - A TUI tool to manage git worktrees"
  homepage "https://github.com/chmouel/lazyworktree"
  version "1.11.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazyworktree"

  on_macos do
    url "https://github.com/chmouel/lazyworktree/releases/download/v#{version}/lazyworktree_Darwin_all.tar.gz"
    sha256 "20ec020761269928112f5efaa7c02ff162776304e06a8b5497e02e660ba525c3"
  end

  on_linux do
    on_intel do
      url "https://github.com/chmouel/lazyworktree/releases/download/v#{version}/lazyworktree_Linux_x86_64.tar.gz"
      sha256 "a97d178f362b9c1a6e1d7e897623c766a8221ed62dd7215c1d7b0ac766f10058"
    end
    on_arm do
      url "https://github.com/chmouel/lazyworktree/releases/download/v#{version}/lazyworktree_Linux_arm64.tar.gz"
      sha256 "260c1c1b1ba2339424471651e6b10c4d0b56c4000ea7555207adc1d17e5337c4"
    end
  end

  # No zap stanza required
end
